### ISSUE TITLE
Unable to fix all the badges in the board

### ISSUE THREAD

**Issue by brundabharadwaj** [vinitshahdeo/holopin-readme-badge#4]
The board size is less such that we cannot have all the badges visible.
Sticking badges on one another does look appealing.
Appealing for a design change! :)

**Comment by TYehan** [comment]
😂
Will do something for it. To select specific sizes or allowing the user to resize the canvas.

BTW, @brundabharadwaj , You should mentioned the issue over @holopin. Not over here. 😂
